
#General configuration settings
[general]
	#Uses custom curio slot for goggles instead of the head slot
	customCurioGoggleSlot = true
	#Enables experimental features
	enableExperimentalFeatures = true
	#Uses custom curio slot for backtank instead of the back slot
	customCurioBacktankSlot = true

